import { Inter } from 'next/font/google';
import Link from 'next/link';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex justify-between p-4 bg-blue-600">
          <Link href={'/csr'}>Go to CSR</Link>
          <Link href={'/ssr'}>Go to SSR</Link>
          <Link href={'/'}>Go to SSG (Home)</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
