import Image from 'next/image';
import Link from 'next/link';

export const metadata = {
  title: 'Statically generated page',
  description: 'Generated by Create Next App.',
};

const fetchTodos = async () => {
  const res = await fetch('https://jsonplaceholder.typicode.com/todos');
  const data = await res.json();
  return data;
};

export default async function Home() {
  const todos = await fetchTodos();
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <h1 className="text-xl text-red-500">Statically generated</h1>
      {todos.map((todo: { id: string; title: string }) => (
        <p key={todo.id}>{todo.title}</p>
      ))}
    </main>
  );
}
