import Link from 'next/link';

export const revalidate = 0;
//	^ every time the user visits the page, it wil re-fetch the data from the server. time is set in minutes.

export const metadata = {
  title: 'Server side rendered page',
  description: 'Generated by create next app',
};

const fetchTodos = async () => {
  const res = await fetch('https://jsonplaceholder.typicode.com/todos');
  const data = await res.json();
  return data;
};

export default async function SSR() {
  const todos = await fetchTodos();
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <h1 className="text-xl text-red-500">Server side rendered</h1>
      {todos.map((todo: { id: string; title: string }) => (
        <p key={todo.id}>{todo.title}</p>
      ))}
    </main>
  );
}
